# Generated by Django 5.0.1 on 2024-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMSys',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskTitle', models.CharField(max_length=500)),
                ('TaskDescription', models.CharField(max_length=500)),
                ('TaskDuedate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('UserEmail', models.CharField(max_length=500)),
                ('Task', models.CharField(max_length=500)),
            ],
        ),
    ]
